language: node_js
node_js:
  - '10'
  - '8'
  - '6'
services:
  - docker
before_install:
  - DB_CONTAINER_NAME="eventstore"
  - docker run -d -p 2113:2113 -p 1113:1113 --name $DB_CONTAINER_NAME eventstore/eventstore
  - sleep 10 # allow eventstore to start
install:
  - npm i
script:
  - npm test
after_script:
  - docker stop $DB_CONTAINER_NAME
  - docker rm $DB_CONTAINER_NAME
